name: Build Image

on: push

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v4

    - id: "auth"
      uses: "google-github-actions/auth@v2"
      with:
        credentials_json: "${{ secrets.GCP_SA_KEY }}"

    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v2"

    - name: "Use gcloud CLI"
      run: "gcloud info"

    -
      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Register gcloud as a Docker credential helper
      run: gcloud auth configure-docker asia-east1-docker.pkg.dev

    #,linux/arm64
    - name: Build and Push the Docker image
      run: |
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c 1-8)
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 \
          -t asia-east1-docker.pkg.dev/homepage-431105/meow/homepage-authorization:latest \
          -t asia-east1-docker.pkg.dev/homepage-431105/meow/homepage-authorization:${{ github.ref_name }} \
          -t asia-east1-docker.pkg.dev/homepage-431105/meow/homepage-authorization:$SHORT_SHA \
          --push .